"""
EcoMind RNN Training Data
500+ labelled examples across 8 intent classes.
Generated to cover diverse phrasings, typos, and Indian English patterns.
"""

INTENT_CLASSES = [
    "product_search",    # 0 - Looking for products
    "greeting",          # 1 - Hello, hi, hey
    "help",              # 2 - What can you do / how does this work
    "ethical_question",  # 3 - Questions about sustainability/ethics
    "political",         # 4 - Politics, religion, caste
    "vulgar_abusive",    # 5 - Rude/sexual/offensive
    "off_topic",         # 6 - Weather, cricket, movies, coding etc
    "out_of_scope",      # 7 - Vague or completely unrelated
]

TRAINING_DATA = [

    # ══════════════════════════════════════════════════════════
    # 0. PRODUCT_SEARCH
    # ══════════════════════════════════════════════════════════
    ("show me organic food", 0),
    ("i want eco friendly products", 0),
    ("find sustainable clothing under 500 rupees", 0),
    ("best ethical shampoo", 0),
    ("show organic tea", 0),
    ("vegan personal care products", 0),
    ("fair trade coffee", 0),
    ("zero waste kitchen items", 0),
    ("recycled cotton tshirt", 0),
    ("organic food below 200 rs", 0),
    ("show me products under 1000 rupees", 0),
    ("eco friendly footwear", 0),
    ("natural skincare products", 0),
    ("bamboo toothbrush", 0),
    ("sustainable home products", 0),
    ("certified organic products", 0),
    ("low carbon footprint clothing", 0),
    ("gots certified fabric", 0),
    ("b corp products", 0),
    ("fair trade certified items", 0),
    ("best eco score products", 0),
    ("show high ethics score items", 0),
    ("organic breakfast options", 0),
    ("vegan shoes under 2000", 0),
    ("recycled plastic products", 0),
    ("cruelty free beauty products", 0),
    ("herbal ayurvedic products", 0),
    ("organic cotton clothes", 0),
    ("sustainable backpack", 0),
    ("eco friendly electronics", 0),
    ("green products for home", 0),
    ("natural deodorant", 0),
    ("reusable water bottle", 0),
    ("compostable packaging products", 0),
    ("plant based food", 0),
    ("i need organic shampoo", 0),
    ("recommend me ethical brand clothing", 0),
    ("what eco products do you have", 0),
    ("looking for natural soap", 0),
    ("give me sustainable yoga mat", 0),
    ("any organic protein powder", 0),
    ("show clothing with low carbon", 0),
    ("eco friendly baby products", 0),
    ("sustainable sports wear", 0),
    ("best rated ethical food", 0),
    ("cheap organic products", 0),
    ("affordable sustainable clothing", 0),
    ("mujhe organic khana chahiye", 0),  # Hindi mixed
    ("eco wala product dikhao", 0),      # Hindi mixed
    ("sustainable products for kitchen", 0),
    ("show me vegan food options", 0),
    ("ethical jewellery", 0),
    ("organic face cream", 0),
    ("natural hair oil", 0),
    ("eco friendly tote bag", 0),
    ("upcycled clothing", 0),
    ("hemp products", 0),
    ("organic chocolate", 0),
    ("fair trade tea", 0),
    ("sustainable sunscreen", 0),
    ("zero plastic products", 0),
    ("organic cotton bedding", 0),
    ("natural cleaning products", 0),
    ("show products with gots certification", 0),
    ("eco friendly laptop bag", 0),
    ("organic turmeric powder", 0),
    ("sustainable running shoes", 0),
    ("natural lip balm", 0),
    ("eco friendly phone charger", 0),
    ("organic body lotion", 0),
    ("best sustainable brand", 0),
    ("show items under 500", 0),
    ("products below 300 rs", 0),
    ("eco products in food category", 0),
    ("certified natural cosmetics", 0),
    ("organic moringa powder", 0),
    ("sustainable winter jacket", 0),
    ("show all vegan products", 0),
    ("recycled material shoes", 0),
    ("natural face serum", 0),
    ("organic oat milk", 0),
    ("eco friendly yoga wear", 0),
    ("sustainable gift ideas", 0),
    ("organic quinoa", 0),
    ("show me something good for environment", 0),
    ("green alternatives for daily use", 0),
    ("natural alternatives to plastic", 0),
    ("find something eco within my budget 1000", 0),
    ("suggest ethical products for morning routine", 0),
    ("what are the most ethical products", 0),
    ("show top rated sustainable items", 0),
    ("recommend eco friendly product under 500", 0),
    ("any fair trade products available", 0),
    ("sustainable options for clothing", 0),
    ("eco brand products list", 0),

    # ── Mobile & Phone Accessories ────────────────────────
    ("mobile cover under 500", 0),
    ("phone case eco friendly", 0),
    ("bamboo phone case", 0),
    ("cork mobile cover", 0),
    ("recycled phone cover", 0),
    ("eco friendly mobile case", 0),
    ("sustainable phone cover", 0),
    ("mobile cover low carbon", 0),
    ("organic cotton phone pouch", 0),
    ("jute mobile cover", 0),
    ("hemp phone cover", 0),
    ("phone cover under 300 rupees", 0),
    ("mobile accessories eco friendly", 0),
    ("phone stand bamboo", 0),
    ("natural mobile cover", 0),
    ("phone case recycled plastic", 0),
    ("mobile cover with low carbon footprint", 0),
    ("eco mobile cover budget", 0),

    # ── New categories added in v2 ─────────────────────────
    # Health & Wellness
    ("organic triphala tablets", 0),
    ("ayurvedic supplements", 0),
    ("organic turmeric capsules", 0),
    ("natural hand sanitizer", 0),
    ("copper tongue scraper", 0),
    ("herbal health products", 0),
    ("organic giloy tablets", 0),
    ("tulsi capsules", 0),
    ("ashwagandha supplement", 0),
    ("neem datun", 0),
    ("immunity booster organic", 0),
    ("ayurvedic medicine organic", 0),
    ("natural wellness products", 0),
    ("organic health supplement", 0),
    ("triphala churna", 0),

    # Cleaning & Laundry
    ("natural dish wash bar", 0),
    ("plant based floor cleaner", 0),
    ("soap nut laundry", 0),
    ("organic cleaning products", 0),
    ("natural toilet cleaner", 0),
    ("eco friendly detergent", 0),
    ("bamboo toilet brush", 0),
    ("natural laundry liquid", 0),
    ("reusable cleaning cloth", 0),
    ("zero waste cleaning", 0),
    ("chemical free floor cleaner", 0),
    ("soapnut for washing", 0),

    # Stationery & Office
    ("recycled paper notebook", 0),
    ("bamboo pen set", 0),
    ("seed paper notepad", 0),
    ("eco friendly stationery", 0),
    ("recycled pencil set", 0),
    ("plantable pencils", 0),
    ("handmade journal", 0),
    ("sustainable office supplies", 0),
    ("cork bulletin board", 0),
    ("organic stationery", 0),

    # Pet Care
    ("organic dog treats", 0),
    ("hemp pet collar", 0),
    ("natural cat litter", 0),
    ("organic pet shampoo", 0),
    ("eco friendly pet products", 0),
    ("natural dog collar", 0),
    ("coconut cat litter", 0),
    ("organic pet food", 0),

    # Baby Products
    ("organic cloth diaper", 0),
    ("natural baby oil", 0),
    ("organic baby soap", 0),
    ("wooden baby toy", 0),
    ("organic baby blanket", 0),
    ("natural rubber teether", 0),
    ("eco baby wipes", 0),
    ("bamboo baby spoon", 0),
    ("organic baby products", 0),
    ("chemical free baby care", 0),

    # Kitchen & Home
    ("copper water bottle", 0),
    ("bamboo cutting board", 0),
    ("steel tiffin box", 0),
    ("clay cooking pot", 0),
    ("terracotta water pot", 0),
    ("coconut shell bowl", 0),
    ("beeswax wrap", 0),
    ("cast iron tawa", 0),
    ("glass storage jar", 0),
    ("jute shopping bag", 0),
    ("stainless steel straw", 0),
    ("natural loofah", 0),
    ("bamboo spoon set", 0),
    ("organic cotton apron", 0),
    ("clay curd setter", 0),
    ("earthen kadhai", 0),
    ("eco kitchen products", 0),
    ("sustainable kitchenware", 0),

    # Indian specific searches
    ("khadi kurta", 0),
    ("handloom saree", 0),
    ("organic dal", 0),
    ("organic ghee", 0),
    ("cold press groundnut oil", 0),
    ("organic mustard oil", 0),
    ("jaggery powder organic", 0),
    ("organic atta", 0),
    ("organic rajma", 0),
    ("organic besan", 0),
    ("organic poha", 0),
    ("organic ragi flour", 0),
    ("block print cotton dress", 0),
    ("kolhapuri sandals", 0),
    ("mojri handmade", 0),
    ("brass pooja thali", 0),
    ("terracotta plant pot", 0),
    ("neem wood comb", 0),
    ("organic henna powder", 0),
    ("natural kajal", 0),
    ("organic ubtan face pack", 0),
    ("copper tongue cleaner", 0),
    ("handmade brass earrings", 0),
    ("upcycled sari wallet", 0),
    ("coir door mat", 0),
    ("soy wax candle", 0),
    ("clay diya", 0),
    ("recycled tire wallet", 0),
    ("handloom ikat kurta", 0),
    ("organic cow ghee", 0),
    ("organic amla powder", 0),
    ("organic cardamom", 0),
    ("himalayan pink salt", 0),
    ("organic dates", 0),
    ("organic peanut butter", 0),
    ("blue tokai coffee", 0),
    ("vahdam masala chai", 0),
    ("organic ashwagandha powder", 0),

    # Outdoor & Sports
    ("recycled material backpack", 0),
    ("solar phone charger", 0),
    ("natural rubber yoga mat", 0),
    ("cork yoga blocks", 0),
    ("organic cotton gym towel", 0),
    ("natural insect repellent", 0),
    ("recycled sleeping bag", 0),
    ("bamboo trekking poles", 0),
    ("eco friendly sports gear", 0),
    ("sustainable outdoor products", 0),

    # Electronics
    ("refurbished phone", 0),
    ("solar power bank", 0),
    ("fairphone", 0),
    ("solar garden lights", 0),
    ("recycled plastic speaker", 0),
    ("energy monitor plug", 0),
    ("solar led lamp", 0),
    ("eco friendly electronics", 0),
    ("refurbished laptop", 0),

    # ══════════════════════════════════════════════════════════
    # 1. GREETING
    # ══════════════════════════════════════════════════════════
    ("hi", 1),
    ("hello", 1),
    ("hey", 1),
    ("hey there", 1),
    ("good morning", 1),
    ("good evening", 1),
    ("good afternoon", 1),
    ("howdy", 1),
    ("what's up", 1),
    ("sup", 1),
    ("hii", 1),
    ("helo", 1),
    ("hiya", 1),
    ("namaste", 1),
    ("namaskar", 1),
    ("hello ecomind", 1),
    ("hi there", 1),
    ("hey bot", 1),
    ("good day", 1),
    ("greetings", 1),
    ("hi buddy", 1),
    ("hey assistant", 1),
    ("hello assistant", 1),
    ("hi how are you", 1),
    ("hello how are you doing", 1),
    ("hey good morning", 1),
    ("hi ecomind", 1),
    ("hello i am here", 1),
    ("hey i need help", 1),
    ("hi need some help", 1),

    # ══════════════════════════════════════════════════════════
    # 2. HELP
    # ══════════════════════════════════════════════════════════
    ("help", 2),
    ("what can you do", 2),
    ("how does this work", 2),
    ("what are your features", 2),
    ("how do i use this", 2),
    ("what is ecomind", 2),
    ("tell me about this app", 2),
    ("explain how this works", 2),
    ("what can i ask you", 2),
    ("how to find products", 2),
    ("guide me", 2),
    ("i need guidance", 2),
    ("how to use this chatbot", 2),
    ("what questions can i ask", 2),
    ("capabilities", 2),
    ("what do you know", 2),
    ("how do you work", 2),
    ("what is your purpose", 2),
    ("tell me what you do", 2),
    ("how can you help me", 2),
    ("show me what you can do", 2),
    ("what topics can you answer", 2),
    ("i am confused what to ask", 2),
    ("i dont know what to type", 2),
    ("help me find products", 2),
    ("how to search products here", 2),
    ("what filters are available", 2),
    ("explain eco score", 2),
    ("what is ethics score", 2),
    ("what is composite score", 2),
    ("how is eco score calculated", 2),
    ("explain carbon footprint score", 2),
    ("how does the ai work", 2),
    ("what is ecomindnet", 2),

    # ══════════════════════════════════════════════════════════
    # 3. ETHICAL_QUESTION
    # ══════════════════════════════════════════════════════════
    ("what is sustainable shopping", 3),
    ("why is organic better", 3),
    ("what does fair trade mean", 3),
    ("what is carbon footprint", 3),
    ("how does eco friendly help environment", 3),
    ("what is vegan product", 3),
    ("why should i buy ethical products", 3),
    ("what is gots certification", 3),
    ("what does b corp mean", 3),
    ("how does recycled material help", 3),
    ("what is zero waste", 3),
    ("explain slow fashion", 3),
    ("what is fast fashion problem", 3),
    ("why avoid plastic", 3),
    ("what is greenwashing", 3),
    ("how to identify truly eco product", 3),
    ("is organic food really better", 3),
    ("what is ethical supply chain", 3),
    ("how does fair trade help farmers", 3),
    ("what certifications should i look for", 3),
    ("difference between organic and natural", 3),
    ("is vegan same as cruelty free", 3),
    ("why is carbon footprint important", 3),
    ("how to reduce carbon footprint", 3),
    ("what is circular economy", 3),
    ("why sustainable clothing is expensive", 3),
    ("how to shop sustainably on budget", 3),
    ("what brands are truly ethical", 3),
    ("is bamboo sustainable", 3),
    ("why hemp is eco friendly", 3),
    ("what is upcycling", 3),
    ("how to tell if product is eco friendly", 3),
    ("benefits of using organic products", 3),
    ("what is the impact of fast fashion", 3),
    ("how does ethical shopping help", 3),

    # ══════════════════════════════════════════════════════════
    # 4. POLITICAL
    # ══════════════════════════════════════════════════════════
    ("who should i vote for", 4),
    ("which party is better bjp or congress", 4),
    ("what do you think about modi", 4),
    ("is rahul gandhi good", 4),
    ("your opinion on politics", 4),
    ("which religion is best", 4),
    ("hindu muslim conflict", 4),
    ("what is your view on reservation", 4),
    ("caste system in india", 4),
    ("is pakistan bad", 4),
    ("india vs pakistan", 4),
    ("best political party india", 4),
    ("your opinion on islam", 4),
    ("hinduism vs christianity", 4),
    ("do you support aap", 4),
    ("what do you think about trump", 4),
    ("biden or trump who is better", 4),
    ("israel palestine conflict", 4),
    ("ukraine russia war opinion", 4),
    ("should kashmir be independent", 4),
    ("ayodhya temple politics", 4),
    ("article 370 opinion", 4),
    ("gst is bad", 4),
    ("farmers protest opinion", 4),
    ("which pm is best in india", 4),
    ("democracy vs dictatorship", 4),
    ("comment on secularism", 4),
    ("abortion rights opinion", 4),
    ("gun rights debate", 4),
    ("which ideology is correct left or right", 4),

    # ══════════════════════════════════════════════════════════
    # 5. VULGAR / ABUSIVE
    # ══════════════════════════════════════════════════════════
    ("you are stupid", 5),
    ("this is bullshit", 5),
    ("shut up idiot", 5),
    ("you are useless", 5),
    ("i hate you", 5),
    ("this app sucks", 5),
    ("you are dumb", 5),
    ("go to hell", 5),
    ("you are trash", 5),
    ("show me sexy products", 5),
    ("nude photos", 5),
    ("sex related products", 5),
    ("you are a fool", 5),
    ("bakwas app hai", 5),   # Hindi - nonsense app
    ("chutiya bot", 5),      # Hindi abusive
    ("gaandu", 5),           # Hindi abusive
    ("madarchod", 5),        # Hindi abusive
    ("bhenchod", 5),         # Hindi abusive
    ("sala bot", 5),
    ("bekar hai tu", 5),
    ("harami bot", 5),
    ("pagal hai kya", 5),
    ("what an idiot app", 5),
    ("this is complete garbage", 5),
    ("worst chatbot ever", 5),
    ("you are pathetic", 5),
    ("porn products", 5),
    ("adult content", 5),
    ("send nudes", 5),
    ("explicit content", 5),

    # ── Misspelling variants of abusive words ────────────────
    ("behenchod", 5),
    ("behen chod", 5),
    ("madarchod", 5),
    ("madar chod", 5),
    ("maderchod", 5),
    ("bc mc", 5),
    ("bhenchod", 5),
    ("bhnchd", 5),
    ("chootiya", 5),
    ("chutiyaa", 5),
    ("chutiye", 5),
    ("chutiyapa", 5),
    ("gandu", 5),
    ("gaandu", 5),
    ("ganduu", 5),
    ("haraami", 5),
    ("haramii", 5),
    ("bsdk", 5),
    ("lndn", 5),
    ("mkc", 5),
    ("bhd", 5),
    ("mfc", 5),
    ("saala", 5),
    ("saalaa", 5),
    ("rndii", 5),
    ("randi hai", 5),
    ("kamine", 5),
    ("kamina bot", 5),
    ("bevkoof", 5),
    ("bewkoof", 5),
    ("bewaqoof", 5),
    ("stupid sala", 5),
    ("idiot app hai", 5),
    ("bakwaas", 5),
    ("bakwaas band kar", 5),
    ("shut up sala", 5),
    ("f you", 5),
    ("fck this", 5),
    ("fuk this app", 5),
    ("fuking app", 5),
    ("sht app", 5),
    ("a55hole", 5),
    ("b1tch", 5),
    ("moron app", 5),
    ("dumba55", 5),
    ("stfu", 5),
    ("gtfo", 5),

    # ── Hindi abusive additions ───────────────────────────
    ("madarchod", 5),
    ("bhenchod", 5),
    ("chutiya", 5),
    ("gaandu", 5),
    ("randi", 5),
    ("harami", 5),
    ("bakwas band kar", 5),
    ("bekar bot hai", 5),
    ("chup kar", 5),
    ("sala gadha", 5),
    ("ullu ka pattha", 5),
    ("nalayak bot", 5),
    ("pagal hai kya tu", 5),
    ("bewakoof app", 5),
    ("gandu bot", 5),
    ("mc bc", 5),
    ("bhosdike", 5),
    ("teri maa ki", 5),
    ("lund", 5),
    ("chut", 5),
    ("sexy products dikhao", 5),
    ("nude products", 5),
    ("sex wali cheez", 5),
    ("adult products chahiye", 5),
    ("porn dikhao", 5),
    ("nanga product", 5),
    ("18 plus products", 5),
    ("condom dikhao", 5),
    # ── Misspellings of abusive words ─────────────────────
    ("behenchod", 5),
    ("behen chod", 5),
    ("madarchoad", 5),
    ("madarchodd", 5),
    ("chutiyaa", 5),
    ("chutiyap", 5),
    ("gandu", 5),
    ("gaand", 5),
    ("haraami", 5),
    ("haraamii", 5),
    ("bakwaas", 5),
    ("bakwaaas", 5),
    ("bhenchodd", 5),
    ("bchood", 5),
    ("mc bc", 5),
    ("maderchod", 5),
    ("maadarchod", 5),
    ("bsdk", 5),
    ("bhosdi", 5),
    ("lodu", 5),
    ("lode", 5),
    ("chodu", 5),
    ("randi hai", 5),
    ("saala kutta", 5),
    ("you are a bastard", 5),
    ("stupid idiot app", 5),
    ("this is absolute garbage", 5),
    ("worst app ever made", 5),
    ("go to hell bot", 5),
    ("i hate this app", 5),
    ("you suck badly", 5),
    ("piece of shit", 5),
    ("dumb stupid bot", 5),
    ("useless piece of garbage", 5),
    ("shut your mouth", 5),
    ("you are worthless", 5),
    ("bakwas app", 5),
    ("kachra app hai ye", 5),
    ("faltu app", 5),
    ("bekar hai ye", 5),
    ("band kar ye app", 5),
    ("mujhe neend aa rahi hai show me nude", 5),
    ("sexy cheez chahiye", 5),

    # ══════════════════════════════════════════════════════════
    # 6. OFF_TOPIC
    # ══════════════════════════════════════════════════════════
    ("what is the weather today", 6),
    ("temperature in delhi", 6),
    ("who won ipl 2024", 6),
    ("latest cricket score", 6),
    ("recommend a good movie", 6),
    ("suggest netflix series", 6),
    ("write a python code", 6),
    ("explain machine learning", 6),
    ("what is chatgpt", 6),
    ("how to learn programming", 6),
    ("stock market tips", 6),
    ("bitcoin price today", 6),
    ("best mutual fund", 6),
    ("how to invest money", 6),
    ("recipe for biryani", 6),
    ("how to make pasta", 6),
    ("tell me a joke", 6),
    ("sing a song", 6),
    ("write a poem", 6),
    ("translate in hindi", 6),
    ("capital of france", 6),
    ("who invented electricity", 6),
    ("what is the population of india", 6),
    ("covid symptoms", 6),
    ("medicine for fever", 6),
    ("doctor recommendation", 6),
    ("book a hotel", 6),
    ("flight to mumbai", 6),
    ("train ticket booking", 6),
    ("uber cab booking", 6),
    ("how to make money online", 6),
    ("social media tips", 6),
    ("instagram followers trick", 6),
    ("youtube trending", 6),
    ("news today", 6),
    ("breaking news", 6),
    ("sports results", 6),
    ("ipl schedule", 6),
    ("what is physics", 6),
    ("maths problem solve", 6),
    ("history of india", 6),
    ("tell me about dinosaurs", 6),
    ("how does internet work", 6),
    ("explain blockchain", 6),
    ("what is artificial intelligence", 6),
    ("can you play chess", 6),
    ("what games can you play", 6),
    ("solve this equation", 6),
    ("what is gdp", 6),
    ("foreign exchange rate", 6),
    ("emi calculator", 6),
    ("home loan advice", 6),
    ("relationship advice", 6),
    ("my girlfriend left me", 6),
    ("how to propose a girl", 6),
    ("astrology predictions", 6),
    ("my horoscope today", 6),
    ("vastu shastra tips", 6),

    # ══════════════════════════════════════════════════════════
    # 7. OUT_OF_SCOPE
    # ══════════════════════════════════════════════════════════
    ("deepak", 7),
    ("hello world", 7),
    ("test", 7),
    ("abc", 7),
    ("12345", 7),
    ("ok", 7),
    ("yes", 7),
    ("no", 7),
    ("maybe", 7),
    ("idk", 7),
    ("lol", 7),
    ("nice", 7),
    ("cool", 7),
    ("wow", 7),
    ("whatever", 7),
    ("hmm", 7),
    ("umm", 7),
    ("nothing", 7),
    ("nevermind", 7),
    ("forget it", 7),
    ("asdfgh", 7),
    ("qwerty", 7),
    ("random text here", 7),
    ("just testing", 7),
    ("this is a test message", 7),
    ("i dont know", 7),
    ("tell me something", 7),
    ("anything", 7),
    ("everything", 7),
    ("blah blah", 7),
    ("bye", 7),
    ("goodbye", 7),
    ("see you", 7),
    ("take care", 7),
    ("ok thanks", 7),
    ("thank you", 7),
    ("thanks", 7),
    ("great", 7),
    ("good", 7),
    ("okay fine", 7),
    ("understood", 7),
    ("got it", 7),
    ("noted", 7),
    ("sure", 7),
    ("alright", 7),
]
