# Generated by Django 4.2.29 on 2026-03-14 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSavedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(default='General', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('materials', models.CharField(blank=True, max_length=500)),
                ('cert', models.CharField(blank=True, max_length=300)),
                ('price', models.FloatField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('eco_score', models.FloatField(blank=True, null=True)),
                ('ethics_score', models.FloatField(blank=True, null=True)),
                ('carbon_level', models.CharField(blank=True, max_length=20)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_assistant.ecouser')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
    ]
