# Generated by Django 4.2.29 on 2026-03-15 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_assistant', '0002_ecouser_otpcode_usersavedproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPCode',
        ),
        migrations.AlterField(
            model_name='usersavedproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EcoUser',
        ),
    ]
